import PDFDocument from 'pdfkit';
import { IUser } from '../models/User';
import { IResumeAnalysis } from '../models/ResumeAnalysis';
import { IRoadmap } from '../models/Roadmap';
import { buildAtsReport } from './ats.service';

const INK = '#0f172a'; // slate-900
const MUTED = '#64748b'; // slate-500
const LIGHT = '#e2e8f0'; // slate-200
const ACCENT = '#f59e0b'; // amber-500

/** Run a full render pass and resolve a PDF as a Buffer. */
const renderPdf = (draw: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 54 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    draw(doc);
    doc.end();
  });

const darkHeader = (doc: PDFKit.PDFDocument, title: string, subtitle: string) => {
  doc.rect(0, 0, 612, 108).fill(INK);
  doc
    .fill('#ffffff')
    .font('Helvetica-Bold')
    .fontSize(22)
    .text('CareerAI', 54, 26);
  doc
    .fill('#f59e0b')
    .font('Helvetica-Bold')
    .fontSize(15)
    .text(title, 54, 56);
  doc
    .fill('#cbd5e1')
    .font('Helvetica')
    .fontSize(10)
    .text(subtitle, 54, 80);
};

const sectionTitle = (doc: PDFKit.PDFDocument, text: string) => {
  doc.moveDown(1.2);
  doc
    .fillColor(INK)
    .font('Helvetica-Bold')
    .fontSize(13)
    .text(text);
  doc.moveDown(0.3);
  doc.moveTo(54, doc.y).lineTo(558, doc.y).strokeColor(LIGHT).lineWidth(1).stroke();
  doc.moveDown(0.5);
};

const progressBar = (doc: PDFKit.PDFDocument, value: number, width = 200) => {
  const barY = doc.y;
  doc.rect(54, barY, width, 8).fill(LIGHT);
  const color = value >= 80 ? '#16a34a' : value >= 60 ? '#ca8a04' : '#dc2626';
  doc.rect(54, barY, Math.max(2, (value / 100) * width), 8).fill(color);
  doc
    .fillColor(INK)
    .font('Helvetica-Bold')
    .fontSize(11)
    .text(` ${value}%`, 54 + width + 8, barY - 3);
  doc.y = barY + 16;
};

const footer = (doc: PDFKit.PDFDocument) => {
  const pages = doc.bufferedPageRange().count;
  for (let i = 1; i <= pages; i++) {
    doc.switchToPage(i - 1);
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(8);
    doc.text(`Generated by CareerAI · ${new Date().toLocaleDateString()}`, 54, 760, { align: 'left' });
    doc.text(`Page ${i} of ${pages}`, 54, 760, { width: 504, align: 'right' });
  }
};

export const buildResumeReportPdf = async (
  user: IUser,
  analysis: IResumeAnalysis
): Promise<Buffer> => {
  const ats = buildAtsReport(analysis.resumeText, []);

  return renderPdf((doc) => {
    darkHeader(
      doc,
      'Resume Report',
      `${user.name || 'User'} · ${user.targetJobRole || 'Career'} · analyzed ${new Date(analysis.createdAt).toLocaleDateString()}`
    );

    doc.y = 130;

    sectionTitle(doc, 'Overall Score');
    progressBar(doc, analysis.overallScore, 300);
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(10)
      .text('Graded across content, structure, skills coverage and impact-driven phrasing.');

    sectionTitle(doc, 'ATS Structure Score');
    progressBar(doc, ats.score, 300);
    doc
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(10)
      .text('Rule-based audit of parseability: contact info, headings, single column, keyword density, action verbs.');

    if (analysis.detectedSkills.length > 0) {
      sectionTitle(doc, 'Detected Skills');
      doc
        .fillColor(INK)
        .font('Helvetica')
        .fontSize(10)
        .text(analysis.detectedSkills.join('  ·  '));
    }

    if (analysis.sectionFeedback.length > 0) {
      sectionTitle(doc, 'Section Feedback');
      analysis.sectionFeedback.forEach((item: { section: string; feedback: string }) => {
        doc
          .fillColor(INK)
          .font('Helvetica-Bold')
          .fontSize(11)
          .text(item.section);
        doc
          .fillColor('#475569')
          .font('Helvetica')
          .fontSize(10)
          .text(item.feedback, { lineGap: 2 });
        doc.moveDown(0.6);
      });
    }

    if (analysis.bulletRewrites.length > 0) {
      sectionTitle(doc, 'Suggested Bullet Rewrites');
      analysis.bulletRewrites.forEach(
        (item: { original: string; suggestion: string; reason: string }) => {
          doc
            .fillColor(MUTED)
            .font('Helvetica-Oblique')
            .fontSize(9)
            .text(`Original:  ${item.original}`);
          doc
            .fillColor(INK)
            .font('Helvetica')
            .fontSize(10)
            .text(`Rewrite:  ${item.suggestion}`);
          doc
            .fillColor(MUTED)
            .font('Helvetica')
            .fontSize(9)
            .text(`Why:  ${item.reason}`);
          doc.moveDown(0.7);
        }
      );
    }

    footer(doc);
  });
};

export const buildRoadmapPdf = async (user: IUser, roadmap: IRoadmap): Promise<Buffer> =>
  renderPdf((doc) => {
    darkHeader(
      doc,
      'Career Roadmap',
      `${user.name || 'User'} · target: ${roadmap.targetRole} · generated ${new Date().toLocaleDateString()}`
    );

    doc.y = 130;

    sectionTitle(doc, 'Overall Progress');
    progressBar(doc, roadmap.overallProgress, 300);

    roadmap.months.forEach((month) => {
      const done = month.tasks.filter((t) => t.isCompleted).length;
      const total = month.tasks.length;

      sectionTitle(doc, `Month ${month.monthNumber} — ${month.focusArea}`);
      doc
        .fillColor(MUTED)
        .font('Helvetica')
        .fontSize(9)
        .text(`Estimated ${month.estimatedHours} hours · ${done}/${total} tasks completed`);

      if (month.topics.length > 0) {
        doc.moveDown(0.3);
        doc
          .fillColor(INK)
          .font('Helvetica-Bold')
          .fontSize(10)
          .text('Topics');
        doc
          .fillColor('#475569')
          .font('Helvetica')
          .fontSize(9)
          .text(month.topics.map((t: string) => `• ${t}`).join('\n'));
      }

      if (month.tasks.length > 0) {
        doc.moveDown(0.3);
        doc
          .fillColor(INK)
          .font('Helvetica-Bold')
          .fontSize(10)
          .text('Tasks');
        month.tasks.forEach((task) => {
          const mark = task.isCompleted ? '✓' : '☐';
          doc
            .fillColor(task.isCompleted ? '#16a34a' : '#475569')
            .font('Helvetica')
            .fontSize(9)
            .text(`${mark}  ${task.description}`, { lineGap: 2 });
        });
      }

      if (month.projects.length > 0) {
        doc.moveDown(0.3);
        doc
          .fillColor(INK)
          .font('Helvetica-Bold')
          .fontSize(10)
          .text('Projects');
        doc
          .fillColor('#475569')
          .font('Helvetica')
          .fontSize(9)
          .text(month.projects.map((p: string) => `• ${p}`).join('\n'));
      }

      if (month.resources.length > 0) {
        doc.moveDown(0.3);
        doc
          .fillColor(INK)
          .font('Helvetica-Bold')
          .fontSize(10)
          .text('Resources');
        doc
          .fillColor('#475569')
          .font('Helvetica')
          .fontSize(9)
          .text(month.resources.map((r: string) => `• ${r}`).join('\n'));
      }

      doc.moveDown(1);
    });

    footer(doc);
  });